### ISSUE TITLE
Undeploy Tasks are broken 

### ISSUE THREAD

**Issue by istairbn** [xebialabs-community/xlr-xldeploy-plugin#38]
Worked in the 2.5.0.
When firing a task, get the following errror

Exception during execution:
AttributeError: type object 'XLDeployClientUtil' has no attribute 'get_deployment_package' in <script> at line number 13

**Comment by jdewinne** [comment]
Do you also have the issue with [v2.7.1](https://github.com/xebialabs-community/xlr-xldeploy-plugin/releases/tag/v2.7.1)?

**Comment by istairbn** [comment]
Yes, same error. I get a different error if I replace the xld_client constructor, but it still fails - looks like there was a big cleanup around this area since 2.5
xld_client = XLDeployClientUtil.create_xldeploy_client(xldeployServer, username, password)

**Comment by jdewinne** [comment]
Thanks for reporting. This should be fixed in v2.8.1
